// Generated by CoffeeScript 1.7.1
(function() {
  window.onload = function() {
    var tour;
    tour = new Tour({
      steps: [
        {
          element: "#series-preview",
          title: "Series Preview",
          content: "Content of my step"
        }, {
          element: "#series-settings",
          title: "seasons Accordian View",
          content: "Content of my step"
        }
      ]
    });
    $('#launch-tour').click(function(e) {
      $('#start-tour-now').click(function(e) {
        tour.init();
        tour.start();
      });
    });
    $('#launch-tour').trigger('click');
  };

}).call(this);
